jobs:
  include:
    - stage: check-links
      install: npm i -g markdown-link-check
      script: markdown-link-check ./README.md
    - stage: commit-OpenAPI
      install: npm i -g swagger2openapi
      script:
        - swagger2openapi src/main/resources/swagger/ga4gh-tool-discovery.yaml -o src/main/resources/swagger/openapi.yaml
      after_success:
        - git checkout -B ${TRAVIS_BRANCH}
        - bash scripts/update-openAPI3.sh
    - stage: build_pages
      language: java
      jdk: oraclejdk8
      script:
      - "gradle wrapper"
      - "chmod +x gradlew"
      - "./gradlew installSwagger buildSwagger asciidoctor"
      after_success:
        - bash scripts/update-ghpages.sh
