dist: xenial
languaige: node_js
node_js:
  - "12"

jobs:
  include:
    - stage: check-links
      install: npm i -g markdown-link-check
      script: markdown-link-check ./README.md
    - stage: commit-OpenAPI
      install: npm i -g swagger2openapi
      script:
        - swagger2openapi openapi/ga4gh-tool-discovery.yaml -o openapi/openapi.yaml
      after_success:
        - git checkout -B ${TRAVIS_BRANCH}
        - bash scripts/openAPI3.sh
    - stage: build_pages
      script:
      - npm ci
      - npx gh-openapi-docs
      after_success:
        - bash scripts/update-ghpages.sh
