dist: xenial
language: node_js
node_js:
  - "12"

jobs:
  include:
    - stage: check-links
      install: npm i -g markdown-link-check
      script: markdown-link-check ./README.md
    - stage: build_pages
      install: npm ci
      script: npx gh-openapi-docs
      after_success:
        - bash scripts/update-ghpages.sh
