dist: xenial
language: java
jdk: openjdk8

jobs:
  include:
    - stage: check-links
      install: npm i -g markdown-link-check
      script: markdown-link-check ./README.md
    - stage: commit-OpenAPI
      install: npm i -g swagger2openapi
      script:
        - swagger2openapi openapi/ga4gh-tool-discovery.yaml -o openapi/openapi.yaml
      after_success:
        - git checkout -B ${TRAVIS_BRANCH}
        - bash scripts/openAPI3.sh
    - stage: build_pages
      script:
      - "gradle wrapper"
      - "chmod +x gradlew"
      - "./gradlew installSwagger buildSwagger asciidoctor"
      after_success:
        - bash scripts/update-ghpages.sh
